import { describe, expect, it, vi } from 'vitest'
import { Certificate, PrivateKey, ProtoWallet } from '@bsv/sdk'
import { CertificateAttempt, families, FlowDeps, Metadata, validateMetadata, requireFamily, liveDeps, wallet, safeError, FlowError } from '../src/utils/certification'
import { getBaseUrl, getBackendUrl } from '../src/utils/getBackendUrl'
const issuer=PrivateKey.fromString('1',16).toPublicKey().toString()
const subject=PrivateKey.fromString('2',16).toPublicKey().toString()
const metadata:Metadata={version:'fixture',issuer:{publicKey:issuer,network:'main'},families:Object.values(families).map(f=>({...f,fields:[...f.fields],enabled:true})),verification:{maxAgeSeconds:900}}
function fixture(){
 const certificate={type:families.email.type,serialNumber:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',subject,certifier:issuer,revocationOutpoint:'00'.repeat(32)+'.0',fields:{email:'encrypted'},signature:'signed-fixture'}
 const deps:FlowDeps={metadata:vi.fn(async()=>metadata),identity:vi.fn(async()=>subject),network:vi.fn(async()=> 'mainnet' as const),acquire:vi.fn(async()=>certificate),verify:vi.fn(async()=>true),stored:vi.fn(async()=>true),publish:vi.fn(async()=>({status:'success'}))}
 return {certificate,deps,attempt:new CertificateAttempt('email',deps),stage:vi.fn()}
}
describe('environment and service descriptor',()=>{
 it.each([['localhost','http://localhost:8080'],['127.0.0.1','http://localhost:8080'],['staging.socialcert.net','https://staging-backend.socialcert.net'],['socialcert.net','https://backend.socialcert.net'],['www.socialcert.net','https://backend.socialcert.net']])('routes %s explicitly',(host,url)=>expect(getBaseUrl(host)).toBe(url))
 it('rejects unknown hosts and telephone sends',()=>{expect(()=>getBaseUrl('socialcert.net.attacker.invalid')).toThrow();expect(()=>getBackendUrl('phone')).toThrow()})
 it('accepts verified shapes without fixed issuer fallback',()=>expect(validateMetadata(metadata).issuer.publicKey).toBe(issuer))
 it.each([{...metadata,issuer:{...metadata.issuer,publicKey:'invalid'}},{...metadata,issuer:{...metadata.issuer,network:'other'}},{...metadata,verification:{maxAgeSeconds:0}}])('rejects malformed descriptor',data=>expect(()=>validateMetadata(data)).toThrow())
 it('rejects disabled or differing family fields',()=>{expect(()=>requireFamily({...metadata,families:[{...metadata.families[0],enabled:false}]},'email')).toThrow();expect(()=>requireFamily({...metadata,families:[{...metadata.families[0],fields:['telephone']}]},'email')).toThrow()})
})
describe('truthful completion and recovery',()=>{
 it('private issuance needs validated signature and inventory; never publishes',async()=>{const f=fixture();await f.attempt.finish({email:'fixture@example.invalid'},false,f.stage);expect(f.attempt.checked).toBe(true);expect(f.deps.verify).toHaveBeenCalledOnce();expect(f.deps.stored).toHaveBeenCalledOnce();expect(f.deps.publish).not.toHaveBeenCalled();expect(f.stage).toHaveBeenLastCalledWith('complete')})
 it.each(['verify','stored'] as const)('cannot claim success when %s fails',async key=>{const f=fixture();vi.mocked(f.deps[key]).mockResolvedValue(false);await expect(f.attempt.finish({email:'fixture@example.invalid'},false,f.stage)).rejects.toThrow();expect(f.attempt.checked).toBe(false);expect(f.stage).toHaveBeenLastCalledWith('error')})
 it.each(['certifier','subject','type'] as const)('rejects wrong receipt %s',async key=>{const f=fixture();f.certificate[key]='wrong';await expect(f.attempt.finish({email:'fixture@example.invalid'},true,f.stage)).rejects.toThrow();expect(f.deps.publish).not.toHaveBeenCalled()})
 it('requires matching wallet network before acquisition',async()=>{const f=fixture();vi.mocked(f.deps.network).mockResolvedValue('testnet');await expect(f.attempt.finish({email:'fixture@example.invalid'},false,f.stage)).rejects.toThrow(/network/);expect(f.deps.acquire).not.toHaveBeenCalled()})
 it('rejects unexpected fields before acquisition',async()=>{const f=fixture();await expect(f.attempt.finish({telephone:'no'},false,f.stage)).rejects.toThrow();expect(f.deps.acquire).not.toHaveBeenCalled()})
 it('resolved publication failure is partial, never success/private; retry reuses receipt',async()=>{const f=fixture();vi.mocked(f.deps.publish).mockResolvedValueOnce({status:'error'});await expect(f.attempt.finish({email:'fixture@example.invalid'},true,f.stage)).rejects.toThrow(/Public copies may already exist/);expect(f.attempt.checked).toBe(true);expect(f.attempt.publicationAttempted).toBe(true);expect(f.attempt.published).toBe(false);expect(f.stage).toHaveBeenLastCalledWith('partial');await f.attempt.finish({email:'fixture@example.invalid'},true,f.stage);expect(f.deps.acquire).toHaveBeenCalledOnce();expect(f.deps.publish).toHaveBeenCalledTimes(2)})
 it('stopping retries preserves possible-disclosure flag',async()=>{const f=fixture();vi.mocked(f.deps.publish).mockRejectedValueOnce(new Error('unavailable'));await expect(f.attempt.finish({email:'fixture@example.invalid'},true,f.stage)).rejects.toThrow();await f.attempt.finish({email:'fixture@example.invalid'},false,f.stage);expect(f.attempt.publicationAttempted).toBe(true);expect(f.deps.acquire).toHaveBeenCalledOnce();expect(f.deps.publish).toHaveBeenCalledOnce()})
 it('unknown issuance will not blindly acquire again',async()=>{const f=fixture();vi.mocked(f.deps.acquire).mockRejectedValue(new Error('outcome unknown'));await expect(f.attempt.finish({email:'fixture@example.invalid'},false,f.stage)).rejects.toThrow();await expect(f.attempt.finish({email:'fixture@example.invalid'},false,f.stage)).rejects.toThrow(/will not issue another/);expect(f.deps.acquire).toHaveBeenCalledOnce()})
 it('concurrent submissions cannot issue twice',async()=>{const f=fixture();await Promise.all([f.attempt.finish({email:'fixture@example.invalid'},false,f.stage),f.attempt.finish({email:'fixture@example.invalid'},false,f.stage)]);expect(f.deps.acquire).toHaveBeenCalledOnce()})
 it('wallet switch before publication fails closed',async()=>{const f=fixture();vi.mocked(f.deps.identity).mockResolvedValueOnce(subject).mockResolvedValueOnce('changed');await expect(f.attempt.finish({email:'fixture@example.invalid'},true,f.stage)).rejects.toThrow(/identity changed/);expect(f.deps.publish).not.toHaveBeenCalled()})
 it('real SDK signature validates fixture and rejects tampered fields',async()=>{const f=fixture();const c=Certificate.fromObject({...f.certificate,signature:undefined});await c.sign(new ProtoWallet(PrivateKey.fromString('1',16)));expect(await c.verify()).toBe(true);c.fields.email='tampered';await expect(c.verify()).rejects.toThrow('Signature is not valid')})
 it('inventory lookup checks later pages',async()=>{const f=fixture();const spy=vi.spyOn(wallet,'listCertificates').mockResolvedValueOnce({totalCertificates:101,certificates:Array.from({length:100},()=>({...f.certificate,serialNumber:'other'}))}).mockResolvedValueOnce({totalCertificates:101,certificates:[f.certificate]});expect(await liveDeps.stored(f.certificate)).toBe(true);expect(spy.mock.calls[1][0].offset).toBe(100);spy.mockRestore()})
 it('external exception details never reach UI',()=>{expect(safeError(new Error('private material'))).not.toContain('private material');expect(safeError(new FlowError('Wait before trying again.'))).toBe('Wait before trying again.')})
})
