// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter } from 'react-router-dom'
const f=vi.hoisted(()=>({request:vi.fn(),load:vi.fn(),acquire:vi.fn(),publish:vi.fn(),identity:vi.fn(),network:vi.fn()}))
vi.mock('../src/utils/certification',async()=>{
 const actual=await vi.importActual<typeof import('../src/utils/certification')>('../src/utils/certification')
 return {...actual,loadMetadata:f.load,request:f.request,wallet:{getPublicKey:f.identity,isAuthenticated:vi.fn(async()=>({authenticated:true}))},CertificateAttempt:class extends actual.CertificateAttempt{constructor(family: 'email'|'x'|'discord'){super(family,{metadata:f.load,identity:async()=>(await f.identity()).publicKey,network:f.network,acquire:f.acquire,verify:async()=>true,stored:async()=>true,publish:f.publish})}}}
})
import CertificationPage from '../src/pages/CertificationPage'
import App from '../src/App'
import { families } from '../src/utils/certification'
const issuer='02'+'a'.repeat(64),subject='03'+'b'.repeat(64)
const metadata={version:'fixture',issuer:{publicKey:issuer,network:'main'},families:Object.values(families).map(item=>({...item,fields:[...item.fields],enabled:true})),verification:{maxAgeSeconds:900}}
function memoryStorage(){const values=new Map<string,string>();return {getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>values.set(key,value),removeItem:(key:string)=>values.delete(key),clear:()=>values.clear(),key:(index:number)=>[...values.keys()][index]??null,get length(){return values.size}}}
beforeEach(()=>{vi.stubGlobal('localStorage',memoryStorage());vi.stubGlobal('sessionStorage',memoryStorage());vi.clearAllMocks();sessionStorage.clear();localStorage.clear();window.history.replaceState(null,'','/EmailVerification');f.load.mockResolvedValue(metadata);f.identity.mockResolvedValue({publicKey:subject});f.network.mockResolvedValue('mainnet');f.publish.mockResolvedValue({status:'success'});f.acquire.mockResolvedValue({type:families.email.type,serialNumber:'fixture',subject,certifier:issuer,revocationOutpoint:'fixture.0',fields:{email:'encrypted'},signature:'fixture'});f.request.mockImplementation(async(_family,data)=>data.funcAction==='sendEmail'?{emailSentStatus:true,sentEmail:data.email}:{verificationStatus:true})})
afterEach(cleanup)
function page(family:'email'|'x'|'discord'='email'){render(<MemoryRouter><CertificationPage family={family}/></MemoryRouter>)}
async function send(){fireEvent.change(screen.getByTestId('email-address'),{target:{value:'fixture@example.invalid'}});await waitFor(()=>expect((screen.getByTestId('send-code') as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByTestId('send-code'));await screen.findByTestId('verification-code')}
async function verify(){fireEvent.change(screen.getByTestId('verification-code'),{target:{value:'123456'}});fireEvent.click(screen.getByTestId('verify-code'))}
describe('actual frontend routes with offline fixture dependencies',()=>{
 it('ignores old global consent and defaults private for every family',()=>{localStorage.setItem('isChecked','true');for(const family of ['email','x','discord'] as const){page(family);expect((screen.getByTestId('publication-consent') as HTMLInputElement).checked).toBe(false);cleanup()}})
 it('email private journey saves receipt without publication',async()=>{page();await send();expect(screen.getByTestId('resend-code')).toBeTruthy();expect(screen.getByTestId('change-address')).toBeTruthy();await verify();await screen.findByTestId('certificate-receipt');expect(f.acquire).toHaveBeenCalledOnce();expect(f.publish).not.toHaveBeenCalled();expect(screen.getByTestId('flow-status').getAttribute('data-stage')).toBe('complete')})
 it('failed code never displays issued receipt and allows correcting it',async()=>{f.request.mockImplementation(async(_family,data)=>data.funcAction==='sendEmail'?{emailSentStatus:true,sentEmail:data.email}:{verificationStatus:false});page();await send();await verify();await screen.findByRole('alert');expect(screen.queryByTestId('certificate-receipt')).toBeNull();expect(f.acquire).not.toHaveBeenCalled();expect((screen.getByTestId('verify-code') as HTMLButtonElement).disabled).toBe(false)})
 it('unconfirmed delivery remains address form; change address clears challenge',async()=>{f.request.mockResolvedValueOnce({emailSentStatus:false});page();fireEvent.change(screen.getByTestId('email-address'),{target:{value:'fixture@example.invalid'}});await waitFor(()=>expect((screen.getByTestId('send-code') as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByTestId('send-code'));await screen.findByRole('alert');expect(screen.queryByTestId('verification-code')).toBeNull();f.request.mockImplementation(async(_family,data)=>({emailSentStatus:true,sentEmail:data.email}));fireEvent.click(screen.getByTestId('send-code'));await screen.findByTestId('verification-code');fireEvent.click(screen.getByTestId('change-address'));expect(screen.queryByTestId('verification-code')).toBeNull()})
 it('publication failure is partial and retry cannot issue twice',async()=>{f.publish.mockResolvedValueOnce({status:'error'});page();fireEvent.click(screen.getByTestId('publication-consent'));await send();await verify();await screen.findByTestId('retry-publication');expect(screen.getByTestId('publication-status').textContent).toContain('Public copies may already exist');expect(screen.getByTestId('flow-status').getAttribute('data-stage')).toBe('partial');fireEvent.click(screen.getByTestId('retry-publication'));await waitFor(()=>expect(screen.getByTestId('flow-status').getAttribute('data-stage')).toBe('complete'));expect(f.acquire).toHaveBeenCalledOnce();expect(f.publish).toHaveBeenCalledTimes(2)})
 it('rejected issuer check blocks provider request',async()=>{f.load.mockRejectedValue(new Error('offline'));page('discord');await screen.findByRole('alert');expect((screen.getByTestId('oauth-start') as HTMLButtonElement).disabled).toBe(true);expect(f.request).not.toHaveBeenCalled()})
 it('denied provider callback has safe actionable recovery and no requests',async()=>{window.history.replaceState(null,'','/DiscordVerification?error=access_denied');page('discord');await screen.findByRole('alert');expect(f.request).not.toHaveBeenCalled();expect(f.acquire).not.toHaveBeenCalled();expect(window.location.search).toBe('')})
 it('mismatched OAuth state cannot exchange or issue',async()=>{window.history.replaceState(null,'','/DiscordVerification?code=fixture-code&state=wrong');sessionStorage.setItem('socialcert-consent-discord',JSON.stringify({subject,reveal:true,created:Date.now(),state:'right'}));page('discord');await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('does not match'));expect(f.request).not.toHaveBeenCalled();expect(f.acquire).not.toHaveBeenCalled()})
 it('matching callback binds consent to wallet/family, cleans URL and issues once',async()=>{window.history.replaceState(null,'','/DiscordVerification?code=fixture-code&state=right');sessionStorage.setItem('socialcert-consent-discord',JSON.stringify({subject,reveal:false,created:Date.now(),state:'right'}));f.request.mockResolvedValue({userName:'fixture',profilePhoto:'https://example.invalid/photo'});f.acquire.mockResolvedValue({type:families.discord.type,serialNumber:'fixture',subject,certifier:issuer,revocationOutpoint:'fixture.0',fields:{userName:'encrypted',profilePhoto:'encrypted'},signature:'fixture'});page('discord');await screen.findByTestId('certificate-receipt');expect(f.request).toHaveBeenCalledOnce();expect(f.acquire).toHaveBeenCalledOnce();expect(f.publish).not.toHaveBeenCalled();expect(window.location.search).toBe('');expect(sessionStorage.getItem('socialcert-consent-discord')).toBeNull()})
 it.each([undefined,null,'yesterday',Date.now()-901000])('malformed or expired consent cannot authorize callback (%s)',async created=>{window.history.replaceState(null,'','/DiscordVerification?code=fixture-code&state=right');sessionStorage.setItem('socialcert-consent-discord',JSON.stringify({subject,reveal:true,created,state:'right'}));page('discord');await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('expired'));expect(f.request).not.toHaveBeenCalled();expect(f.acquire).not.toHaveBeenCalled()})
 it('X callback requires the exact token for this sign-in attempt',async()=>{window.history.replaceState(null,'','/XVerification?oauth_token=wrong&oauth_verifier=fixture');sessionStorage.setItem('socialcert-consent-x',JSON.stringify({subject,reveal:true,created:Date.now(),requestToken:'right'}));page('x');await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('does not match'));expect(f.request).not.toHaveBeenCalled()})
 it('matching X callback issues a private receipt once',async()=>{window.history.replaceState(null,'','/XVerification?oauth_token=right&oauth_verifier=fixture');sessionStorage.setItem('socialcert-consent-x',JSON.stringify({subject,reveal:false,created:Date.now(),requestToken:'right'}));f.request.mockResolvedValue({userName:'fixture',profilePhoto:'https://example.invalid/photo'});f.acquire.mockResolvedValue({type:families.x.type,serialNumber:'fixture',subject,certifier:issuer,revocationOutpoint:'fixture.0',fields:{userName:'encrypted',profilePhoto:'encrypted'},signature:'fixture'});page('x');await screen.findByTestId('certificate-receipt');expect(f.acquire).toHaveBeenCalledOnce();expect(f.publish).not.toHaveBeenCalled();expect(window.location.search).toBe('')})
 it('issuance exception remains unknown with no false receipt or automatic retry',async()=>{f.acquire.mockRejectedValue(new Error('wallet outcome unknown'));page();await send();await verify();await screen.findByText(/Issuance outcome is unknown/);expect(screen.queryByTestId('certificate-receipt')).toBeNull();expect(f.acquire).toHaveBeenCalledOnce();expect(screen.queryByTestId('verify-code')).toBeNull()})
 it('old phone deep link cannot send SMS',async()=>{window.history.replaceState(null,'','/PhoneVerification/EnterPhoneCode');render(<App/>);expect(screen.getByTestId('phone-unavailable')).toBeTruthy();expect(f.request).not.toHaveBeenCalled();expect(f.acquire).not.toHaveBeenCalled()})
 it('forged success route cannot display issued receipt',async()=>{window.history.replaceState(null,'','/EmailVerification/VerifyResult/success');render(<App/>);expect(screen.queryByTestId('certificate-receipt')).toBeNull();expect(screen.getByText(/A result URL cannot confirm/)).toBeTruthy()})
})
